### ISSUE TITLE
Branch data-modules isn't converting any data

### ISSUE THREAD

**Issue by reinvantveer** [histograph/data#34]
Unclear on how this should work, but at the moment it isn't. Switched to histograph-config data-modules branch, with a  freshly pulled [data-geonames](https://github.com/histograph/data-geonames): 

``` yaml
data:                                       # Data module options (http://github.com/histograph/data)
  modulePrefix: data-
  baseDir: /home/reinv/data/Github/histograph
  generatedDir: /home/reinv/data/Github/histograph/generated-data
  modules:
    geonames:
      countries:
        - NL
      extraUris: ./extra-uris.json
```

But on:
reinv@lingui:~/data/Github/histograph/data$ node index.js --all

```
Using data modules in /home/reinv/data/Github/histograph/data-*
  Saving data to /home/reinv/data/Github/histograph/generated-data

No data modules found...

Usage: node index.js [--all] [--steps [step1,step2,...]] [--config /path/to/config.yml] [module ...]
```
